  - name: check if shorewall is installed
    apt: "name={{ item }} state=present"
    with_items:
      - shorewall
    tags:
        - firewall

  - name: configure shorewall
    lineinfile: "dest={{ item.filename }} line=\"{{ item.line }}\" state=present create=yes"
    with_items:
        - { filename: "/etc/shorewall/interfaces", line: "ext eth0" }
        - { filename: "/etc/shorewall/zones", line: "fw firewall" }
        - { filename: "/etc/shorewall/zones", line: "ext ipv4" }
        - { filename: "/etc/shorewall/policy", line: "fw  all ACCEPT info" }
        - { filename: "/etc/shorewall/policy", line: "all all DROP info" }
        - { filename: "/etc/shorewall/rules", line: "ACCEPT:info ext fw tcp 22" }
        - { filename: "/etc/shorewall/rules", line: "ACCEPT:info fw  ext all" }
    register: shorewallconfig
    tags:
        - firewall

  - name: force reload shorewall
    shell: "shorewall check && shorewall restart"
    when: shorewallconfig.changed
    tags:
        - firewall

  - name: start shorewall at boot
    copy: src=shorewall dest=/etc/default/shorewall
    tags:
        - firewall
